twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    date:
        format: d-m-Y
        timezone: Europe/Paris
    paths:
        '%kernel.project_dir%/assets/styles': styles
    globals:
        geoapify_key: '%geoapify_key%'
when@test:
    twig:
        strict_variables: true
